# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit testing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 src --count --max-complexity=10 --max-line-length=127 --statistics --ignore E402
    - name: Run unit test
      run: python tests/testBaselineRules.py
    - name: Run unit test of BaselineRuleToGlobalNetPol
      run: python tests/testBaselineRuleToGlobalNetPol.py
